Create Routes
TilegenGena/MentorshipApp pull request #2
Opened 2024-01-10 16:34 UTC by TilegenGena

Summary:
- Create routes * dashboard * login * user-profile
- Add notification icon
- Reorder `app.component.html`
- Move `mentorship.app.module.ts` into `mentorship` folder

Test:
Run Server, Client
Main page with links (dashboard, user-profile, login) leads to new pages

<img width="1439" alt="Снимок экрана 2024-01-10 в 22 34 20" src="https://github.com/TilegenGena/MentorshipApp/assets/93535962/b702e506-9fd0-42e0-8a56-d6fd0fe0cf71">

2024-01-11 08:43 UTC, hopeaisulu requested changes
Looks great!
Please remove for now the extra components that we don't need.

2024-01-11 08:43 UTC, hopeaisulu commented on client/src/app/app-routing.module.ts
> +];
Eventually there will be only two pages, Dashboard and Advice wall. Other will be a button with a modal pop up window. You can remove login and user profile from the route. But make a buttons: Mentors, Mentorship, Bell icon, button with the username, logout button.

So combining these pages and button will look as follows:
Dashboard, Advice Wall, Mentors, Mentorship, bell icon, Aisulu Abdraimova, logout button.

2024-01-11 08:43 UTC, hopeaisulu commented on client/src/app/app.component.html
> +</nav>
please remove extra pages and add buttons.You can rename one of these to "Advice Wall" or create new.

2024-01-11 08:43 UTC, hopeaisulu commented on client/src/app/login/login.component.html
> +<p>login works!</p>
For now we don't need this login page, please remove, we will add later.

2024-01-12 10:21 UTC, hopeaisulu approved these changes

2024-01-12 10:21 UTC, merged

2024-01-13 13:46 UTC, networkflow commented
Thanks for including a screenshot on the PR, very helpful! Overall looks pretty good to me, it's still early in the app so I'm not 100% sure what your plans are but seems like a good start.